### ISSUE TITLE
Installation Error The 'sklearn' PyPI package is deprecated, use 'scikit-learn' rather than 'sklearn' for pip commands

### ISSUE THREAD

**Issue by aadityadengle** [HemantKArya/lsHotword#1]
The error occurred on Raspberry Pi Zero 2W. may need to update the package requirements, with scikit-learn, as sklearn has been deprecated.

![image](https://github.com/HemantKArya/lsHotword/assets/6919655/59dc7af5-cb82-4231-a2a7-e68dc1ef2001)

**Comment by HemantKArya** [comment]
If you have found any workaround for this library for RaspberryPi than I appreciate if you make PR using custom forked.
